substitutions:
  _SERVICE: llmhive-orchestrator
  _REGION: us-east1
  _IMAGE: gcr.io/llmhive-orchestrator/llmhive-orchestrator

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build the image using the Dockerfile in the repo root
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_IMAGE}:$COMMIT_SHA', '.']

  # 2) Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_IMAGE}:$COMMIT_SHA']

  # 3) Deploy the image to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_IMAGE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # Use update-env-vars so image-defined defaults (like PYTHONPATH) are preserved
      - '--update-env-vars=DATABASE_URL=sqlite:////tmp/llmhive.db,GIT_COMMIT=$COMMIT_SHA'
      - '--quiet'

images:
  - '${_IMAGE}'
