options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/llmhive/llmhive:$COMMIT_SHA', '.']

images:
  - 'gcr.io/$PROJECT_ID/llmhive/llmhive:$COMMIT_SHA'
