# Example configuration for deploying LLMHIVE to Cloud Run.
# Build image: gcloud builds submit --tag gcr.io/PROJECT/llmhive
# Deploy: gcloud run deploy llmhive --image gcr.io/PROJECT/llmhive --region=REGION \
#   --platform=managed --allow-unauthenticated --set-env-vars DB_URL=... \
#   --set-env-vars ENABLE_DEBATE=1 --set-env-vars ENABLE_FACTCHECK=1
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llmhive
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT/llmhive
          env:
            - name: PORT
              value: "8080"
            - name: ENABLE_DEBATE
              value: "1"
            - name: ENABLE_FACTCHECK
              value: "1"
