# Cloud Build configuration for LLMHive Backend
# This file configures automated deployments to Google Cloud Run
#
# Prerequisites:
# 1. Enable Cloud Build API in your GCP project
# 2. Enable Cloud Run API in your GCP project
# 3. Create secrets in Secret Manager:
#    - openai-api-key
#    - anthropic-api-key
#    - grok-api-key
#    - gemini-api-key
#    - deepseek-api-key
#    - tavily-api-key
#    - pinecone-api-key
#    - api-key (internal auth)
#    - stripe-secret-key
#    - stripe-webhook-secret
#
# Trigger setup:
#   gcloud builds triggers create github \
#     --repo-name=LLMHIVE \
#     --repo-owner=YOUR_GITHUB_USERNAME \
#     --branch-pattern="^main$" \
#     --build-config=llmhive/cloudbuild.yaml

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'llmhive'

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:$COMMIT_SHA'
    waitFor: ['build']

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:latest'
    waitFor: ['build']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'llmhive-orchestrator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '20'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'ALLOW_STUB_PROVIDER=true,LOG_LEVEL=INFO,ENVIRONMENT=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--update-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,ANTHROPIC_API_KEY=anthropic-api-key:latest,GROK_API_KEY=grok-api-key:latest,GEMINI_API_KEY=gemini-api-key:latest,DEEPSEEK_API_KEY=deepseek-api-key:latest,TAVILY_API_KEY=tavily-api-key:latest,PINECONE_API_KEY=pinecone-api-key:latest,OPENROUTER_API_KEY=open-router-key:latest,API_KEY=api-key:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest'
    waitFor: ['push', 'push-latest']

  # Step 5: Run health check
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Waiting for deployment to complete..."
        sleep 30
        SERVICE_URL=$(gcloud run services describe llmhive-orchestrator --region=us-east1 --format='value(status.url)' --project=$PROJECT_ID)
        echo "Service URL: $SERVICE_URL"
        curl -f "$SERVICE_URL/health" || echo "Health check pending (service may still be starting)"
    waitFor: ['deploy']

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

# Store images in GCR
images:
  - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/llmhive-orchestrator:latest'

# Build timeout (15 minutes)
timeout: '900s'

# Tags for organization
tags:
  - 'llmhive'
  - 'orchestrator'
  - 'production'
