# cloudbuild.yaml — build, push, deploy to Cloud Run with correct Secret Manager mapping
# NOTE: This copy lives under llmhive/ so Cloud Build triggers configured with
#       Location: /llmhive/cloudbuild.yaml continue to work. The root-level
#       cloudbuild.yaml is the canonical source; keep them in sync.

options:
  logging: CLOUD_LOGGING_ONLY

# Adjust if your region/service ever changes
substitutions:
  _REGION: us-east1
  _SERVICE_NAME: llmhive-orchestrator

timeout: "1200s"

steps:
  # 1) Build the Docker image (no cache to avoid stale deployments)
  - id: "Build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        TAG="${COMMIT_SHA:-$BUILD_ID}"
        IMAGE="gcr.io/${PROJECT_ID}/llmhive-orchestrator:$${TAG}"
        echo "Building $${IMAGE} with --no-cache ..."
        docker build --no-cache -t "$${IMAGE}" .

  # 2) Push the image
  - id: "Push image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        TAG="${COMMIT_SHA:-$BUILD_ID}"
        IMAGE="gcr.io/${PROJECT_ID}/llmhive-orchestrator:$${TAG}"
        echo "Pushing $${IMAGE} ..."
        docker push "$${IMAGE}"

  # 3) Deploy to Cloud Run with ALL required secrets
  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        TAG="${COMMIT_SHA:-$BUILD_ID}"
        IMAGE="gcr.io/${PROJECT_ID}/llmhive-orchestrator:$${TAG}"
        echo "Deploying $${IMAGE} to Cloud Run service ${_SERVICE_NAME} in region ${_REGION} on port 8080..."
        
        # Build secrets list - only include secrets that exist in Secret Manager
        SECRETS="OPENAI_API_KEY=openai-api-key:latest"
        SECRETS="$${SECRETS},GROK_API_KEY=grok-api-key:latest"
        SECRETS="$${SECRETS},GEMINI_API_KEY=gemini-api-key:latest"
        SECRETS="$${SECRETS},TAVILY_API_KEY=tavily-api-key:latest"
        
        # Add optional secrets if they exist (check first to avoid deployment failure)
        if gcloud secrets describe anthropic-api-key --project=${PROJECT_ID} >/dev/null 2>&1; then
          SECRETS="$${SECRETS},ANTHROPIC_API_KEY=anthropic-api-key:latest"
          echo "Adding ANTHROPIC_API_KEY secret"
        fi
        if gcloud secrets describe deepseek-api-key --project=${PROJECT_ID} >/dev/null 2>&1; then
          SECRETS="$${SECRETS},DEEPSEEK_API_KEY=deepseek-api-key:latest"
          echo "Adding DEEPSEEK_API_KEY secret"
        fi
        if gcloud secrets describe pinecone-api-key --project=${PROJECT_ID} >/dev/null 2>&1; then
          SECRETS="$${SECRETS},PINECONE_API_KEY=pinecone-api-key:latest"
          echo "Adding PINECONE_API_KEY secret"
        fi
        
        echo "Deploying with secrets: $${SECRETS}"
        
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "$${IMAGE}" \
          --region "${_REGION}" \
          --platform managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="ALLOW_STUB_PROVIDER=true,LOG_LEVEL=INFO" \
          --set-secrets="$${SECRETS}"
        echo "Deploy step complete."

  # 4) Verify mapping and health check
  - id: "Verify deployment"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - -c
      - |
        set -euo pipefail
        echo "=== Cloud Run Configuration ==="
        gcloud run services describe "${_SERVICE_NAME}" --region "${_REGION}" \
          --format='table(
            spec.template.spec.containers[0].env[].name:label=ENV,
            spec.template.spec.containers[0].env[].valueFrom.secretKeyRef.name:label=SECRET_ID)'
        
        echo ""
        echo "=== Service URL ==="
        SERVICE_URL=$(gcloud run services describe "${_SERVICE_NAME}" --region "${_REGION}" --format='value(status.url)')
        echo "Service URL: $${SERVICE_URL}"
        
        echo ""
        echo "=== Health Check ==="
        sleep 10  # Wait for service to be ready
        curl -s -o /dev/null -w "Health check response: %{http_code}\n" "$${SERVICE_URL}/health" || echo "Health check failed (service may still be starting)"

