version: "3.9"

services:
  api:
    build: .
    command: uvicorn llmhive.app.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      DATABASE_URL: postgresql+psycopg://llmhive:llmhive@db:5432/llmhive
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: llmhive
      POSTGRES_USER: llmhive
      POSTGRES_PASSWORD: llmhive
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
