apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llmhive.fullname" . }}
  labels:
    {{- include "llmhive.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "llmhive.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "llmhive.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.workloadIdentity.ksaName }}
      serviceAccountName: {{ .Values.workloadIdentity.ksaName }}
      {{- end }}
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              {{- if .Values.useExternalSecret }}
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
              {{- else }}
              value: ""
              {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
