apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llmhive.fullname" . }}
  labels:
    {{- include "llmhive.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "llmhive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llmhive.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.workloadIdentity.ksaName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
