import type { MetadataRoute } from "next"

const baseUrl = "https://www.llmhive.ai"

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    "",
    "/landing",
    "/promo",
    "/about",
    "/contact",
    "/demo",
    "/pricing",
    "/terms",
    "/privacy",
    "/cookies",
    "/press",
    "/alternatives",
    "/best-for",
    "/faq",
    "/case-studies",
    "/case-studies/legal-ops-contract-review",
    "/case-studies/finance-analyst-reporting",
    "/case-studies/healthcare-clinical-summaries",
    "/case-studies/support-tier1-deflection",
    "/case-studies/saas-product-enablement",
    "/use-cases",
    "/use-cases/enterprise-ai",
    "/use-cases/engineering-and-product",
    "/use-cases/research-and-knowledge",
    "/use-cases/marketing-and-content",
    "/use-cases/customer-support",
    "/best-ai-assistant-for",
    "/best-ai-assistant-for/engineers",
    "/best-ai-assistant-for/marketers",
    "/best-ai-assistant-for/researchers",
    "/best-ai-assistant-for/support-teams",
    "/best-ai-assistant-for/executives",
    "/comparisons/best-ai-assistant-for",
    "/comparisons/best-ai-assistant-for/engineers",
    "/comparisons/best-ai-assistant-for/marketers",
    "/comparisons/best-ai-assistant-for/researchers",
    "/comparisons/best-ai-assistant-for/support-teams",
    "/comparisons/best-ai-assistant-for/executives",
    "/comparisons/industries",
    "/comparisons/industries/legal-teams",
    "/comparisons/industries/finance-teams",
    "/comparisons/industries/healthcare-teams",
    "/comparisons/industries/support-teams",
    "/comparisons/industries/saas-teams",
    "/comparisons/industries/legal/harvey",
    "/comparisons/industries/legal/casetext",
    "/comparisons/industries/legal/lexisnexis",
    "/comparisons/industries/legal/westlaw",
    "/comparisons/industries/legal/ironclad",
    "/comparisons/industries/finance/alphasense",
    "/comparisons/industries/finance/bloomberg",
    "/comparisons/industries/finance/factset",
    "/comparisons/industries/finance/pitchbook",
    "/comparisons/industries/finance/refinitiv",
    "/comparisons/industries/healthcare/nuance",
    "/comparisons/industries/healthcare/epic",
    "/comparisons/industries/healthcare/cerner",
    "/comparisons/industries/healthcare/athenahealth",
    "/comparisons/industries/healthcare/meditech",
    "/comparisons/industries/support/zendesk-ai",
    "/comparisons/industries/support/freshdesk",
    "/comparisons/industries/support/helpscout",
    "/comparisons/industries/support/gorgias",
    "/comparisons/industries/support/servicenow",
    "/comparisons/industries/saas/intercom",
    "/comparisons/industries/saas/hubspot",
    "/comparisons/industries/saas/pendo",
    "/comparisons/industries/saas/appcues",
    "/comparisons/industries/saas/userpilot",
    "/comparisons/industries/roles",
    "/comparisons/industries/roles/legal-teams-vs-harvey",
    "/comparisons/industries/roles/legal-teams-vs-casetext",
    "/comparisons/industries/roles/legal-teams-vs-lexisnexis",
    "/comparisons/industries/roles/legal-teams-vs-westlaw",
    "/comparisons/industries/roles/legal-teams-vs-ironclad",
    "/comparisons/industries/roles/finance-teams-vs-alphasense",
    "/comparisons/industries/roles/finance-teams-vs-bloomberg",
    "/comparisons/industries/roles/finance-teams-vs-factset",
    "/comparisons/industries/roles/finance-teams-vs-pitchbook",
    "/comparisons/industries/roles/finance-teams-vs-refinitiv",
    "/comparisons/industries/roles/healthcare-teams-vs-nuance",
    "/comparisons/industries/roles/healthcare-teams-vs-epic",
    "/comparisons/industries/roles/healthcare-teams-vs-cerner",
    "/comparisons/industries/roles/healthcare-teams-vs-athenahealth",
    "/comparisons/industries/roles/healthcare-teams-vs-meditech",
    "/comparisons/industries/roles/support-teams-vs-zendesk-ai",
    "/comparisons/industries/roles/support-teams-vs-freshdesk",
    "/comparisons/industries/roles/support-teams-vs-helpscout",
    "/comparisons/industries/roles/support-teams-vs-gorgias",
    "/comparisons/industries/roles/support-teams-vs-servicenow",
    "/comparisons/industries/roles/saas-teams-vs-intercom",
    "/comparisons/industries/roles/saas-teams-vs-hubspot",
    "/comparisons/industries/roles/saas-teams-vs-pendo",
    "/comparisons/industries/roles/saas-teams-vs-appcues",
    "/comparisons/industries/roles/saas-teams-vs-userpilot",
    "/industries",
    "/industries/legal",
    "/industries/finance",
    "/industries/healthcare",
    "/industries/support",
    "/industries/saas",
    "/comparisons",
    "/comparisons/llmhive-vs-chatgpt",
    "/comparisons/llmhive-vs-claude",
    "/comparisons/llmhive-vs-gemini",
    "/comparisons/llmhive-vs-perplexity",
    "/comparisons/llmhive-vs-copilot",
    "/comparisons/llmhive-vs-jasper",
    "/comparisons/llmhive-vs-notion-ai",
    "/comparisons/llmhive-vs-glean",
    "/comparisons/llmhive-vs-writer",
    "/comparisons/llmhive-vs-langchain",
    "/comparisons/llmhive-vs-openrouter",
    "/comparisons/llmhive-vs-vertex-ai",
    "/comparisons/llmhive-vs-openai-enterprise",
    "/comparisons/llmhive-vs-anthropic-team",
    "/comparisons/llmhive-vs-gemini-advanced",
    "/comparisons/llmhive-vs-salesforce-einstein",
    "/comparisons/llmhive-vs-amazon-q",
    "/comparisons/llmhive-vs-ibm-watsonx",
    "/comparisons/llmhive-vs-cohere",
    "/comparisons/llmhive-vs-mistral",
    "/comparisons/llmhive-vs-azure-openai",
    "/comparisons/llmhive-vs-databricks-mosaic",
    "/comparisons/llmhive-vs-snowflake-cortex",
    "/comparisons/llmhive-vs-legal-ai",
    "/comparisons/llmhive-vs-finance-ai",
    "/comparisons/llmhive-vs-healthcare-ai",
    "/comparisons/llmhive-vs-support-ai",
    "/comparisons/llmhive-vs-saas-ai",
  ]

  const now = new Date()

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: now,
    changeFrequency: "weekly",
    priority: route === "" || route === "/landing" ? 1 : 0.7,
  }))
}
