// AUTO-GENERATED by scripts/sync_frontier_surfaces.py — do not edit by hand.
// Source: data/generated/frontier_roster.json

export const MARKETING_OPENAI_FLAGSHIP = "GPT-5.5 Pro"

export const MARKETING_FEATURED_LINE = "GPT-5.5 Pro · Claude Opus 4.8 · Gemini 3.1 Pro · Grok 4.3 · DeepSeek V3.2 · 350+ more"

export const MARKETING_FEATURED_ORCHESTRATION_STACK = "GPT-5.5 Pro + Claude Opus 4.8 + Gemini 3.1 Pro"

export const MARKETING_META_DESCRIPTION_MODELS = "GPT-5.5 Pro, Claude Opus 4.8, Gemini 3.1 Pro, Grok 4.3, DeepSeek V3.2 and 350+ more"
