// AUTO-GENERATED by scripts/sync_frontier_surfaces.py — do not edit by hand.
// Source: data/generated/frontier_roster.json

export const MARKETING_OPENAI_FLAGSHIP = "GPT-6 Astra"

export const MARKETING_FEATURED_LINE = "GPT-6 Astra · Claude Opus 5 · Claude Fable 5.1 · Gemini 3.1 Pro · Grok 4.6 · Kimi K3 · 350+ more"

export const MARKETING_FEATURED_ORCHESTRATION_STACK = "GPT-6 Astra + Claude Opus 5 + Gemini 3.1 Pro"

export const MARKETING_META_DESCRIPTION_MODELS = "GPT-6 Astra, Claude Opus 5, Claude Fable 5.1, Gemini 3.1 Pro, Grok 4.6, Kimi K3 and 350+ more"
