#!/usr/bin/env python3
"""Generate frontier model surfaces from data/generated/frontier_roster.json.

Outputs (do not edit by hand):
  - lib/models.generated.ts
  - lib/marketing/featured-models.generated.ts
  - lib/marketing/usecase-category-rankings.generated.json
  - llmhive/src/llmhive/app/data/frontier_paid_catalog.generated.json
  - llmhive/src/llmhive/app/data/frontier_registry.generated.json

Usage:
  python scripts/sync_frontier_surfaces.py
  python scripts/sync_frontier_surfaces.py --verify-openrouter
  python scripts/sync_frontier_surfaces.py --check   # exit 1 if outputs stale
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Set

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "llmhive" / "src"))

from llmhive.app.knowledge.usecase_category_rankings import (  # noqa: E402
    build_category_rankings_json,
)

ROSTER_PATH = ROOT / "data" / "generated" / "frontier_roster.json"
OUT_MODELS_TS = ROOT / "lib" / "models.generated.ts"
OUT_MARKETING_TS = ROOT / "lib" / "marketing" / "featured-models.generated.ts"
OUT_CATEGORY_RANKINGS_JSON = ROOT / "lib" / "marketing" / "usecase-category-rankings.generated.json"
OUT_PAID_JSON = ROOT / "llmhive" / "src" / "llmhive" / "app" / "data" / "frontier_paid_catalog.generated.json"
OUT_REGISTRY_JSON = ROOT / "llmhive" / "src" / "llmhive" / "app" / "data" / "frontier_registry.generated.json"

# Flagship families: if OpenRouter adds a newer slug in these families, drift check fails.
FLAGSHIP_FAMILY_PATTERNS = [
    r"^anthropic/claude-opus-4\.\d+$",
    r"^openai/gpt-5\.\d+(-pro)?$",
    r"^google/gemini-3\.1-pro",
    r"^x-ai/grok-4\.\d+$",
    r"^deepseek/deepseek-v4-pro$",
    r"^moonshotai/kimi-k2\.6$",
]


def _ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _fetch_openrouter_ids() -> Set[str]:
    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/models",
        headers={"Accept": "application/json"},
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    out: Set[str] = set()
    for row in payload.get("data") or []:
        mid = row.get("id")
        if isinstance(mid, str) and mid.strip():
            out.add(mid.strip().lower())
    return out


def _verify_openrouter(roster: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    try:
        or_ids = _fetch_openrouter_ids()
    except Exception as exc:
        return [f"Could not fetch OpenRouter catalog: {exc}"]

    for section in ("ui_models", "paid_catalog"):
        for item in roster.get(section) or []:
            slug = str(item.get("model_id") or item.get("id") or "").lower()
            if slug and slug not in or_ids:
                errors.append(f"Roster slug not on OpenRouter: {slug}")
    return errors


def _generate_models_ts(ui_models: List[Dict[str, Any]]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/sync_frontier_surfaces.py — do not edit by hand.",
        f"// Source: data/generated/frontier_roster.json",
        'import type { Model } from "./types"',
        "",
        "export const CURATED_MODEL_ENTRIES: Model[] = [",
    ]
    for m in ui_models:
        caps = m.get("capabilities") or {}
        lines.extend(
            [
                "  {",
                f"    id: {_ts_string(m['model_id'])},",
                f"    name: {_ts_string(m['name'])},",
                f"    provider: {_ts_string(m['provider'])},",
                f"    description: {_ts_string(m['description'])},",
                "    capabilities: {",
                f"      vision: {'true' if caps.get('vision') else 'false'},",
                f"      codeExecution: {'true' if caps.get('codeExecution', caps.get('code_execution')) else 'false'},",
                f"      webSearch: {'true' if caps.get('webSearch', caps.get('web_search')) else 'false'},",
                f"      reasoning: {'true' if caps.get('reasoning') else 'false'},",
                "    },",
                "  },",
            ]
        )
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def _generate_marketing_ts(marketing: Dict[str, Any]) -> str:
    return "\n".join(
        [
            "// AUTO-GENERATED by scripts/sync_frontier_surfaces.py — do not edit by hand.",
            f"// Source: data/generated/frontier_roster.json",
            "",
            f"export const MARKETING_OPENAI_FLAGSHIP = {_ts_string(marketing['openai_flagship'])}",
            "",
            f"export const MARKETING_FEATURED_LINE = {_ts_string(marketing['featured_line'])}",
            "",
            f"export const MARKETING_FEATURED_ORCHESTRATION_STACK = {_ts_string(marketing['featured_orchestration_stack'])}",
            "",
            f"export const MARKETING_META_DESCRIPTION_MODELS = {_ts_string(marketing['meta_description_models'])}",
            "",
        ]
    )


def _generate_paid_catalog_json(paid_catalog: List[Dict[str, Any]]) -> str:
    payload = {
        "_generated": True,
        "_source": "data/generated/frontier_roster.json",
        "paid_catalog": paid_catalog,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _generate_registry_json(registry: List[Dict[str, Any]]) -> str:
    payload = {
        "_generated": True,
        "_source": "data/generated/frontier_roster.json",
        "registry_additions": registry,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _category_rankings_stable_json(text: str) -> str:
    """Compare category rankings ignoring volatile generated_at timestamp."""
    if not text.strip():
        return ""
    payload = json.loads(text)
    payload.pop("generated_at", None)
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def generate_all(roster: Dict[str, Any]) -> Dict[str, bool]:
    changed: Dict[str, bool] = {}
    changed["models_ts"] = _write_if_changed(
        OUT_MODELS_TS, _generate_models_ts(roster.get("ui_models") or [])
    )
    changed["marketing_ts"] = _write_if_changed(
        OUT_MARKETING_TS, _generate_marketing_ts(roster.get("marketing") or {})
    )
    changed["category_rankings_json"] = _write_if_changed(
        OUT_CATEGORY_RANKINGS_JSON, build_category_rankings_json()
    )
    changed["paid_json"] = _write_if_changed(
        OUT_PAID_JSON, _generate_paid_catalog_json(roster.get("paid_catalog") or [])
    )
    changed["registry_json"] = _write_if_changed(
        OUT_REGISTRY_JSON, _generate_registry_json(roster.get("registry_additions") or [])
    )
    return changed


def _manifest_hash(roster: Dict[str, Any]) -> str:
    canonical = json.dumps(roster, sort_keys=True, separators=(",", ":"))
    return _sha(canonical)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify-openrouter", action="store_true")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated outputs would change (CI drift guard)",
    )
    args = parser.parse_args()

    if not ROSTER_PATH.is_file():
        print(f"ERROR: Missing roster source: {ROSTER_PATH}", file=sys.stderr)
        return 1

    roster = json.loads(ROSTER_PATH.read_text(encoding="utf-8"))
    roster.setdefault("updated_at", datetime.now(timezone.utc).isoformat())

    if args.verify_openrouter:
        errors = _verify_openrouter(roster)
        if errors:
            for err in errors:
                print(f"ERROR: {err}", file=sys.stderr)
            return 1
        print("OpenRouter verification passed.", file=sys.stderr)

    expected = {
        "models_ts": _generate_models_ts(roster.get("ui_models") or []),
        "marketing_ts": _generate_marketing_ts(roster.get("marketing") or {}),
        "category_rankings_json": _category_rankings_stable_json(build_category_rankings_json()),
        "paid_json": _generate_paid_catalog_json(roster.get("paid_catalog") or []),
        "registry_json": _generate_registry_json(roster.get("registry_additions") or []),
    }
    actual = {
        "models_ts": OUT_MODELS_TS.read_text(encoding="utf-8") if OUT_MODELS_TS.is_file() else "",
        "marketing_ts": OUT_MARKETING_TS.read_text(encoding="utf-8") if OUT_MARKETING_TS.is_file() else "",
        "category_rankings_json": _category_rankings_stable_json(
            OUT_CATEGORY_RANKINGS_JSON.read_text(encoding="utf-8")
            if OUT_CATEGORY_RANKINGS_JSON.is_file()
            else ""
        ),
        "paid_json": OUT_PAID_JSON.read_text(encoding="utf-8") if OUT_PAID_JSON.is_file() else "",
        "registry_json": OUT_REGISTRY_JSON.read_text(encoding="utf-8") if OUT_REGISTRY_JSON.is_file() else "",
    }

    if args.check:
        stale = [k for k, v in expected.items() if v != actual.get(k, "")]
        if stale:
            print(f"Generated surfaces stale: {', '.join(stale)}", file=sys.stderr)
            print("Run: python scripts/sync_frontier_surfaces.py", file=sys.stderr)
            return 1
        print("Generated surfaces are up to date.", file=sys.stderr)
        return 0

    changed = generate_all(roster)
    any_changed = any(changed.values())
    print(f"Roster hash: {_manifest_hash(roster)[:12]}", file=sys.stderr)
    for name, did in changed.items():
        print(f"  {'updated' if did else 'unchanged'}: {name}", file=sys.stderr)
    if not any_changed:
        print("All generated surfaces already current.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
